# Generated by Django 6.0.1 on 2026-02-06 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_create_admin_user'),
        ('core', '0003_add_orders_OrderItem_manual'),
    ]

    operations = [
    ]
